### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by Thomas-Langlais** [Thomas-Langlais/t-lang#8]
All programming languages use variables. therefore I too shall add them.

I want it to look something along the line of the following.
`let foo = 1`

**Comment by Thomas-Langlais** [comment]
# Grammer updates
The language will need a few lexer updates to implement the following
> I want it to look something along the line of the following.
> `let foo = 1`

 - identifier token type - the `foo` part
 - new operation token type - `=`
 - reserved identifier list (aka keywords) - `let` cannot be a valid identifier as the interpreter can't decide on what token type it should be

**Comment by Thomas-Langlais** [comment]
# Interpreter updates
Variable data must be stored somewhere inside the runtime.

[this reference](https://en.wikipedia.org/wiki/Symbol_table) describes what all programming languages use to store variable/symbol data.

Since the language currently only supports a REPL environment, the interpreter needs a global table.

## TODO
 - [x] Define a symbol table struct
 - [x] Implement the interpret function for assigning/using a variable
 - [x] Attach the symbol table to the execution context

The symbol table only needs to hold variable data right now, so it can use a identifier/number hashmap.
```rust

struct SymbolTable {
    symbols: HashMap<String, i64>, // this will need to be a enum for selecting the different types of numbers available
    parent_context: Option<Box<ExecutionContext>>
}
```
This way, if the interpreter can't find the symbol in the current table, it can go to the parent context and recursively search until we hit the global table.

**Comment by Thomas-Langlais** [comment]
# Global symbol table functioning
I revamped the execution context to use a reference of a table,
and changed the symbol table to use a RefCell for the key/value
contents.

## Notes
I fell into the OOP trap of trying to have a mutable reference
throughout the recursive interpreter stacktrace (this can lead to
dangling pointers in C). Instead, I opted to only accept a reference
to a symbol table and have a mutable interior key/value store.

## Restrictions
The limitation now is that in order to return the value of a symbol,
we can no longer use `self.symbols.get`. It has to borrow the
refcell, which disallows returning a reference from the borrowed refcell
value.
