### ISSUE TITLE
comparison/logical expressions

### ISSUE THREAD

**Issue by Thomas-Langlais** [Thomas-Langlais/t-lang#9]
I want the language to do comparisons and logical operations.

Add comparison operations:
 - `<`
 - `<=`
 - `>`
 - `>=`
 - `!`
 - `!=`
 - `==`

Add Logical operations:
- `&&`
- `||`

**Comment by Thomas-Langlais** [comment]
# preface
the parser handles BEDMAS priority by selecting the expected grammar function based on the current token state.

the current grammar rules
```
expression = KW:LET IDENTIFIER EQ expression 
           = term (PLUS|MINUS term)*

term       = factor (MUL|DIV factor)*

factor     = atom
           = (PLUS|MINUS) factor

atom       = INT|FLOAT|IDENTIFIER
           = LParen expression RParen
```

The each item in the grammar function stack of the parser represents the **token** that the **grammar function** is responsible for **parsing**.

# operator priority notes
We can determine the operation/bracket priority
1. `(` and `)`
1. `*` and `/`
2. `+` and `-`

The reason is, as the parser is recursing into the grammar functions, the first non-variable/unary related token it can parse is the brackets, because of this execution chain `expression -> term -> factor -> atom -> LParen`

# new operation priorities
Both sets of operations shall have priority over multiplication and division, but lower priority than brackets.
Since brackets should **always** be top priority.

**Comment by Thomas-Langlais** [comment]
# proposed grammar
```
expression = KW:LET IDENTIFIER EQ expr 
           = expr

expr       = comp_expr ((AND|OR) comp_expr)*

comp_expr  = NOT comp_expr
           = arith_expr ((EE|NE|LT|GT|LTE|GTE) arith_expr)*

arith_expr = term (PLUS|MINUS term)*

term       = factor (MUL|DIV factor)*

factor     = atom
           = (PLUS|MINUS) factor

atom       = INT|FLOAT|IDENTIFIER
           = LParen expression RParen
```

This should work, but I'll need to implement it before I can verify the priority is correct.

# Todo
 - [x] Implement the new tokens in the lexer:
   - [x] `EE`, `NE`, `NOT`
   - [x] `LT`, `LTE`
   - [x] `GT`, `GTE`
   - [x] `AND`, `OR`
 - [x] Implement the comparison/logical operation grammar functions
   - [x] Update `expression`
   - [x] Implement `expr`
   - [x] Implement `comp_expr`
   - [x] Implement `arith_expr`
 - [x] Implement the interpret trait for the new operations

**Comment by Thomas-Langlais** [comment]
# Symbol table changes
Now what the interpreter can use boolean logic, it should also be able to set true or false onto variables.
This includes making changes for reading/writing to the symbol table.

## Problems
The symbol table currently allows the interpreter to read/write to any value.
```
let a = 1
a
```
This is the behavior programmers expect. But there are no exceptions, like `false` and `true`.

As of how it's implemented, this is also allowed.
```
let false = 500
let true = 0
```
To stop the programmer from overwriting the constant identifiers, changes need to be made on the symbol table.

## Solution
Change the symbol table to use a hashmap value struct that defines the rule to disallow writing to `true` and `false`

```rust
pub enum SymbolValue {
    Int(i64),
    Float(f64),
}

pub struct SymbolEntry {
    value: SymbolValue,
    is_constant: bool,
}

pub struct SymbolTable<'a> {
    pub symbols: RefCell<HashMap<String, SymbolEntry>>,
    parent_context: Option<&'a ExecutionContext<'a>>,
}
```

This way, the symbol table can return a runtime error if it receives a write call on a constant symbol

# Todo
 - [x] add symbol entry implementation
 - [x] return runtime error handling
 - [x] add starting symbols to global sym table
 - [x] add bool symbol values
